---
# dirty hack that I'm not proud of
# mostly due to lack of support for URL resource in k8 module
- name: install cert-manger CRDs & namespace
  command: "kubectl apply -f {{ item }}"
  loop: "{{ cert_manager_required_manifests }}"
  changed_when: false

- name: install cert-manager helm chart
  include_role:
    name: nagonzalez.helm
    tasks_from: charts
  vars:
    helm_charts:
      - "{{ cert_manager_helm_chart }}"
