---
- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: add docker yum repo
  yum_repository:
    name: docker-ce-stable
    description: 'Docker CE Stable - $basearch'
    baseurl: 'https://download.docker.com/linux/centos/7/$basearch/stable'
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: install docker-ce
  package:
    name: "{{ item }}"
  loop:
    - "docker-ce-18.09.6-3.el7"
    - "docker-ce-cli-18.09.6-3.el7"
    - "containerd.io-1.2.5-3.1.el7"

- name: ensure docker is started
  service:
    name: docker
    state: started
    enabled: true

- name: add rancher user to docker group
  user:
    name: "{{ rancher_user }}"
    append: yes
    groups: docker
