---
- name: add cloudlfare secret
  k8s:
    state: present
    definition: "{{ lookup('template', 'letsencrypt-secret.yml.j2') }}"

- name: add let's encrypt issuer
  k8s:
    state: present
    definition: "{{ lookup('template', 'letsencrypt-issuer.yml.j2') }}"

- name: patch rancher ingress
  k8s:
    state: present
    definition: "{{ lookup('template', 'rancher-ingress.yml.j2') }}"
