---
# tasks file for ansible-role-rancher

# configue tiller connectivity if required
- include: tiller.yml
  when: l_helm_host is not defined or l_helm_port is not defined

# install rancher helm chart
- include: rancher.yml

# patch ingress when using ClusterIssuer
- include: ingress.yml
  when: cert_manager_cluster_issuer | bool
