---
# tasks file for ansible-role-rancher

# ensure we can talk to helm
- include: helm.yml

# install rancher via helm
- include: rancher.yml

# configure Let's Encrypt
- include: lets-encrypt.yml
  when: letsencrypt_setup | bool
