---
# tasks file for ansible-role-rancher

# install cert-manager helm chart
- include: cert-manger.yml

# install rancher helm chart
- include: rancher.yml

# configure Let's Encrypt
- include: lets-encrypt.yml
  when: letsencrypt_setup | bool
