---
# tasks file for ansible-role-rancher

# configure dns records
- include: dns.yml
  when: rancher_create_dns_records | bool

# create rancher vms
- include: vm.yml
  when: rancher_create_vms | bool

# install docker
- include: docker.yml

# install rancher requirements
- include: requirements.yml

# install rancher
- include: install.yml
  tags:
    - rancher_install
