---
- name: Install cert-manager helm chart
  helm:
    host: "{{ l_helm_host }}"
    port: "{{ l_helm_port }}"
    chart:
      name: cert-manager
      version: v0.5.2
      source:
        type: git
        location: https://github.com/jetstack/cert-manager.git
        reference: 'v0.5.2'
        path: contrib/charts/cert-manager
    state: present
    name: cert-manager
    namespace: kube-system

- name: Install rancher helm chart
  helm:
    host: "{{ l_helm_host }}"
    port: "{{ l_helm_port }}"
    chart:
      name: rancher
      version: "{{ rancher_version }}"
      source:
        type: repo
        location: https://releases.rancher.com/server-charts/stable
    state: present
    name: rancher
    namespace: cattle-system
    values: "{{ rancher_helm_chart_values }}"
