---
- name: install required yum packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - epel-release
    - git
    - python2-pip
    - python2-openshift-0.8.8-1.el7

- name: install required pip packages
  pip:
    name: "{{ item }}"
  loop:
    - pyhelm==0.1.5

- name: add tiller service account
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: tiller
        namespace: kube-system

- name: make tiller service account cluster-admin
  k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: tiller
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: tiller
          namespace: kube-system

- name: Set up Helm and Tiller.
  command: helm init --service-account tiller
  register: helm_init_result
  changed_when: "'already installed' not in helm_init_result.stdout"

- name: Get Tiller's ClusterIP.
  k8s:
    api_version: v1
    kind: Service
    name: tiller-deploy
    namespace: kube-system
  register: tiller_service

- name: Set the Helm host and port
  set_fact:
    l_helm_host: "{{ tiller_service.result.spec.clusterIP }}"
    l_helm_port: "{{ tiller_service.result.spec.ports[0].port }}"

- name: Wait for Tiller to become responsive.
  wait_for:
    host: "{{ l_helm_host }}"
    port: "{{ l_helm_port }}"
    state: started

- name: Install cert-manager helm chart
  helm:
    host: "{{ l_helm_host }}"
    port: "{{ l_helm_port }}"
    chart:
      name: cert-manager
      version: v0.5.2
      source:
        type: git
        location: https://github.com/jetstack/cert-manager.git
        reference: 'v0.5.2'
        path: contrib/charts/cert-manager
    state: present
    name: cert-manager
    namespace: kube-system

- name: Install rancher helm chart
  helm:
    host: "{{ l_helm_host }}"
    port: "{{ l_helm_port }}"
    chart:
      name: rancher
      version: "{{ rancher_version }}"
      source:
        type: repo
        location: https://releases.rancher.com/server-charts/stable
    state: present
    name: rancher
    namespace: cattle-system
    values: "{{ rancher_helm_chart_values }}"
