---
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: gather facts
  setup:

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: set net.bridge.bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: download rke
  get_url:
    url: https://github.com/rancher/rke/releases/download/v0.2.4/rke_linux-amd64
    dest: /sbin/rke
    mode: 0755

- name: download kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.14.3/bin/linux/amd64/kubectl
    dest: /sbin/kubectl
    mode: 0755

- name: download helm
  unarchive:
    src: "https://storage.googleapis.com/kubernetes-helm/helm-v2.14.1-linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true

- name: copy helm
  copy:
    src: /tmp/linux-amd64/helm
    dest: /sbin/helm
    remote_src: true
    mode: 0755

- name: add ssh private key
  copy:
    dest: /home/packer/.ssh/id_rsa
    owner: packer
    group: packer
    mode: 0600
    content: |
        -----BEGIN RSA PRIVATE KEY-----
        changeme
        -----END RSA PRIVATE KEY-----
