---
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: gather facts
  setup:

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: set net.bridge.bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: download rke
  get_url:
    url: "https://github.com/rancher/rke/releases/download/v{{ rancher_rke_version }}/rke_linux-amd64"
    dest: /sbin/rke
    mode: 0755

- name: download kubectl
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ rancher_kubectl_version }}/bin/linux/amd64/kubectl"
    dest: /sbin/kubectl
    mode: 0755

- name: download helm
  unarchive:
    src: "https://storage.googleapis.com/kubernetes-helm/helm-v{{ rancher_helm_version }}-linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true

- name: copy helm
  copy:
    src: /tmp/linux-amd64/helm
    dest: /sbin/helm
    remote_src: true
    mode: 0755

- name: add ssh private key
  copy:
    dest: "/home/{{ rancher_user }}/.ssh/id_rsa"
    owner: "{{ rancher_user }}"
    group: "{{ rancher_user }}"
    mode: 0600
    content: "{{ rancher_ssh_key }}"
