---
- name: install required yum packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - epel-release
    - git
    - python2-pip
    - python2-openshift

- name: install required pip packages
  pip:
    name: "{{ item }}"
  loop:
    - future
    - pyhelm
