---
- name: create directory to hold rke configs
  file:
    state: directory
    path: "/opt/rancher"
    owner: "{{ rancher_user }}"
    group: "{{ rancher_user }}"
    mode: 0700

- name: copy rancher-cluster.yml
  template:
    src: rancher-cluster.yml.j2
    dest: "/opt/rancher/rancher-cluster.yml"
    owner: "{{ rancher_user }}"
    group: "{{ rancher_user }}"
    mode: 0600
  register: l_rancher_cluster_yml

- name: kick off rke installer
  become: true
  become_user: "{{ rancher_user }}"
  command: "rke up --config ./rancher-cluster.yml"
  args:
    chdir: "/opt/rancher/"
  changed_when: l_rancher_cluster_yml.changed

- name: ensure .kube directory exists
  file:
    state: directory
    dest: "{{ item }}"
    owner: "{{ rancher_user }}"
    group: "{{ rancher_user }}"
  loop:
    - "/home/{{ rancher_user }}/.kube"
    - "/root/.kube"

- name: symlink ~/.kube/config to kube_config_rancher-cluster.yml
  file:
    state: link
    src: /opt/rancher/kube_config_rancher-cluster.yml
    dest: "{{ item }}"
    owner: "{{ rancher_user }}"
    group: "{{ rancher_user }}"
  loop:
    - "/home/{{ rancher_user }}/.kube/config"
    - "/root/.kube/config"
