---
- name:  create rancher VMs
  vmware_guest:
    hostname: "{{ rancher_vmware_config['hostname'] }}"
    username: "{{ rancher_vmware_config['username'] }}"
    password: "{{ rancher_vmware_config['password'] }}"
    validate_certs: no
    name: "{{ item.hostname }}"
    folder: "{{ rancher_vmware_config['folder'] }}"
    datacenter: "{{ rancher_vmware_config['datacenter'] }}"
    cluster: "{{ rancher_vmware_config['cluster'] }}"
    datastore: "{{ rancher_vmware_config['datastore'] }}"
    hardware: "{{ rancher_vmware_config['hardware'] }}"
    guest_id: "{{ rancher_vmware_config['guest_id'] }}"
    networks:
      - name: "{{ rancher_vmware_config['network_name'] }}"
        ip: "{{ item.ip }}"
        netmask: "{{ item.netmask }}"
        gateway: "{{ item.gw }}"
    disk: "{{ rancher_vmware_config['disk'] }}"
    wait_for_ip_address: True
    template: "{{ rancher_vmware_config['template'] }}"
    customization:
      hostname: "{{ item.hostname }}"
      domain: "{{ rancher_dns_zone }}"
      dns_servers: "{{ item.dns_servers }}"
      dns_suffix: "{{ rancher_dns_zone }}"
    state: present
  delegate_to: 127.0.0.1
  run_once: true
  changed_when: false
  loop: "{{ rancher_nodes }}"
