---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: rancher
    box: centos/7
    cpus: 1
    memory: 4096
    interfaces:
      - auto_config: true
        ip: 172.28.128.3
        network_name: private_network
        type: static
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      rancher:
        rancher_nodes:
          - hostname: rancher
            role: '[controlplane,etcd,worker]'
            ip: 172.28.128.3
            netmask: 255.255.255.0
            gw: 172.28.128.1
            dns_servers:
              - 172.31.3.2
  lint:
    name: ansible-lint
    options:
      x: [
        "204"  # Lines should be no longer than 160 chars
      ]
verifier:
  name: testinfra
  lint:
    name: flake8
