---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: ansible-role-rke-node
    - role: ansible-role-rke
    - role: ansible-role-helm
    - role: ansible-role-cert-manager
    - role: ansible-role-rancher
